### ISSUE TITLE
Exception are not reported as issues

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/flaplid#52]
```2018-02-13T21:40:46,490 [main] INFO  horse.wtf.flaplid.checks.Check - Running check [dns:dns-www-graylog-org-a#emergency].
2018-02-13T21:40:46,507 [main] ERROR horse.wtf.flaplid.Main - Check failed.
 java.lang.RuntimeException: java.lang.RuntimeException: DNS lookup failed with error: REFUSED
        at horse.wtf.flaplid.checks.dns.DNSCheck.check(DNSCheck.java:139) ~[flaplid-0.5.jar:?]
        at horse.wtf.flaplid.checks.Check.run(Check.java:56) ~[flaplid-0.5.jar:?]
        at horse.wtf.flaplid.Main.main(Main.java:222) [flaplid-0.5.jar:?]
Caused by: java.lang.RuntimeException: DNS lookup failed with error: REFUSED
        at horse.wtf.flaplid.checks.dns.DNSCheck.check(DNSCheck.java:82) ~[flaplid-0.5.jar:?]
        ... 2 more
```

This did not generate an issue

**Comment by lennartkoopmann** [comment]
it did report it
